const KEY="catalogo-express.v1";
const presets={almacen:{name:"Almacén",tag:"Productos ricos, atención cercana.",color:"#1f6b52",products:["Pan casero","Huevos","Mermelada artesanal"]},emprendimiento:{name:"Mi emprendimiento",tag:"Hecho con dedicación.",color:"#8b4f32",products:["Producto destacado","Producto especial"]},servicios:{name:"Mi servicio",tag:"Soluciones simples y profesionales.",color:"#315a8a",products:["Servicio principal","Servicio adicional"]}};
const base=()=>({preset:"almacen",name:"",tag:"",phone:"",address:"San Patricio del Chañar",hours:"Lun a sáb · 9 a 20 hs",payment:"Efectivo · Transferencia",delivery:"Retiro en el local · Consultar envío",color:"#1f6b52",products:[]});
let state=load();
function load(){try{return Object.assign(base(),JSON.parse(localStorage.getItem(KEY)||"{}"))}catch{return base()}}
function save(){localStorage.setItem(KEY,JSON.stringify(state))}
function esc(v){return String(v??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]))}
function money(v){return v?"$ "+esc(v):"Consultar"}
function applyPreset(id){const p=presets[id];state.preset=id;state.name=p.name;state.tag=p.tag;state.color=p.color;state.products=p.products.map((name,i)=>({name,price:i===0?"":"",description:"",emoji:["🥖","🥚","🍓","✨"][i]||"✨"}));save();render()}
function addProduct(){state.products.push({name:"Nuevo producto",price:"",description:"",emoji:"✨"});save();render();setTimeout(()=>document.querySelector(".product:last-child input")?.focus(),0)}
function removeProduct(i){state.products.splice(i,1);save();render()}
function update(path,value){const a=path.split(".");if(a[0]==="product")state.products[+a[1]][a[2]]=value;else state[a[0]]=value;save();renderPreview()}
function wa(){const digits=(state.phone||"").replace(/\D/g,"");return digits?"https://wa.me/"+digits:"#"}
function render(){document.querySelector("#app").innerHTML='<div class="shell"><header class="topbar"><div class="brand">CATÁLOGO EXPRESS<small>Fábrica de catálogos · Ocarina</small></div><div class="top-actions"><button class="btn ghost" id="reset">Nuevo</button><button class="btn primary" id="share">Compartir</button></div></header><main class="workspace"><section class="panel builder"><div class="eyebrow">Constructor</div><h1 class="title">Tu catálogo, listo para WhatsApp.</h1><p class="muted">Cargá los datos una vez. La vista de la derecha se actualiza al instante.</p><div class="section"><h3>1 · Punto de partida</h3><div class="field"><label>Estilo</label><select id="preset"></select></div></div><div class="section"><h3>2 · Negocio</h3><div class="field"><label>Nombre</label><input data-k="name" placeholder="Ej. Almacén La Esquina"></div><div class="field"><label>Frase</label><input data-k="tag" placeholder="Una frase corta"></div><div class="grid2"><div class="field"><label>WhatsApp</label><input data-k="phone" placeholder="549299..."></div><div class="field"><label>Color</label><input data-k="color" type="color"></div></div><div class="field"><label>Dirección</label><input data-k="address"></div></div><div class="section"><h3>3 · Información útil</h3><div class="field"><label>Horarios</label><input data-k="hours"></div><div class="field"><label>Medios de pago</label><input data-k="payment"></div><div class="field"><label>Entrega / retiro</label><input data-k="delivery"></div></div><div class="section"><div style="display:flex;justify-content:space-between;align-items:center"><h3>4 · Productos</h3><span class="eyebrow">'+state.products.length+' cargados</span></div><div id="products"></div><button class="add" id="add">+ Agregar producto</button></div><div class="section"><div class="toolbar"><button class="btn primary" id="share2">Crear enlace de WhatsApp</button><button class="btn" id="reset2">Empezar de nuevo</button></div><div id="status"></div></div></section><section class="panel preview-wrap"><div class="preview-frame"><div class="phone" id="preview"></div></div></section></main></div>';
const sel=document.querySelector("#preset");sel.innerHTML=Object.entries(presets).map(([k,p])=>'<option value="'+k+'">'+p.name+"</option>").join("");sel.value=state.preset;
document.querySelectorAll("[data-k]").forEach(el=>el.value=state[el.dataset.k]||"");
document.querySelector("#products").innerHTML=state.products.map((p,i)=>'<div class="product"><div class="product-head"><span class="product-name">Producto '+(i+1)+'</span><button class="icon-btn" data-remove="'+i+'">×</button></div><div class="grid2"><div class="field"><label>Nombre</label><input data-p="'+i+'.name" value="'+esc(p.name)+'"></div><div class="field"><label>Precio</label><input data-p="'+i+'.price" value="'+esc(p.price)+'" placeholder="Ej. 4500"></div></div><div class="field"><label>Descripción</label><input data-p="'+i+'.description" value="'+esc(p.description)+'" placeholder="Qué recibe el cliente"></div><div class="field"><label>Ícono</label><input data-p="'+i+'.emoji" value="'+esc(p.emoji)+'" maxlength="4"></div></div>').join("");bind();renderPreview()}
function renderPreview(){const p=document.querySelector("#preview");if(!p)return;const valid=state.name.trim()&&state.products.some(x=>x.name.trim());const cards=state.products.length?state.products.map(x=>'<article class="card"><div class="thumb">'+esc(x.emoji||"✨")+'</div><div><h4>'+esc(x.name||"Producto sin nombre")+'</h4>'+(x.description?"<p>"+esc(x.description)+"</p>":"")+'<div class="price">'+money(x.price)+"</div></div></article>").join(""):'<div class="empty">Agregá tu primer producto para verlo acá.</div>';p.innerHTML='<div class="store-hero" style="background:'+esc(state.color)+'"><div class="tag">'+esc(state.tag||"Tu catálogo digital")+'</div><h1>'+esc(state.name||"Nombre de tu negocio")+'</h1><div class="small">'+esc(state.address||"Agregá tu ubicación")+'</div></div><div class="store-info">'+(state.hours?"<div>🕘 "+esc(state.hours)+"</div>":"")+(state.payment?"<div>💳 "+esc(state.payment)+"</div>":"")+(state.delivery?"<div>📦 "+esc(state.delivery)+"</div>":"")+'</div><div class="catalog"><div class="catalog-title">Productos</div>'+cards+'<button class="cta" style="background:'+esc(state.color)+'" id="waButton">'+(state.phone?"Pedir por WhatsApp":"Cargá WhatsApp")+"</button>"+(valid?'<div class="status">✓ Catálogo listo para compartir</div>':'<div class="status danger">Falta nombre o al menos un producto.</div>')+"</div></div>";document.querySelector("#waButton").onclick=()=>{if(state.phone)window.open(wa(),"_blank");else alert("Cargá el número de WhatsApp primero.")}}
function bind(){document.querySelector("#preset").onchange=e=>applyPreset(e.target.value);document.querySelectorAll("[data-k]").forEach(el=>el.oninput=e=>update(el.dataset.k,e.target.value));document.querySelectorAll("[data-p]").forEach(el=>el.oninput=e=>{const a=el.dataset.p.split(".");update("product."+a[0]+"."+a[1],e.target.value)});document.querySelectorAll("[data-remove]").forEach(el=>el.onclick=()=>removeProduct(+el.dataset.remove));document.querySelector("#add").onclick=addProduct;document.querySelectorAll("#reset,#reset2").forEach(b=>b.onclick=()=>{if(confirm("¿Empezar un catálogo nuevo?")){state=base();save();render()}});document.querySelectorAll("#share,#share2").forEach(b=>b.onclick=share)}
async function share(){const digits=(state.phone||"").replace(/\D/g,"");if(!digits){alert("Cargá el número de WhatsApp antes de compartir.");return}const url="https://wa.me/"+digits+"?text="+encodeURIComponent("Hola, quiero consultar el catálogo de "+(state.name||"tu negocio")+"." );try{await navigator.clipboard.writeText(url);showStatus("Enlace de WhatsApp copiado.")}catch{prompt("Copiá este enlace:",url)}}
function showStatus(msg){const s=document.querySelector("#status");if(s)s.innerHTML='<div class="status">✓ '+esc(msg)+"</div>"}
render();