export const SITE_BASE="https://eliasmartinezcultural-glitch.github.io/catalogo-generador/";
export function slugify(value){return String(value||"catalogo").normalize("NFD").replace(/[\u0300-\u036f]/g,"").toLowerCase().replace(/[^a-z0-9]+/g,"-").replace(/^-+|-+$/g,"").slice(0,48)||"catalogo"}
export function publicPath(catalog){return "catalogos/"+slugify(catalog.name)+"-"+String(catalog.id||"").slice(0,8)+"/"}
export function publicUrl(catalog){return SITE_BASE+publicPath(catalog)}
export function buildPublicationHTML(state,meta={}){
  const b=state.business||{},a=state.appearance||{},items=(state.products||[]).map(p=>`<article class="item"><div class="thumb">${p.image?`<img src="${p.image}" alt="">`:p.emoji||"•"}</div><div><h2>${esc(p.name)}</h2>${a.showDescriptions&&p.description?`<p>${esc(p.description)}</p>`:""}</div>${a.showPrices&&p.price?`<strong class="price">$${esc(p.price)}</strong>`:""}</article>`).join("");
  const wa=String(b.phone||"").replace(/\D/g,"");
  const waUrl=wa?`https://wa.me/${wa}?text=${encodeURIComponent("Hola, vi el catálogo de "+(b.name||"tu negocio"))}`:"#";
  return `<!doctype html><html lang="es"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="description" content="${esc(b.tag||b.name||"Catálogo digital")}"><meta property="og:title" content="${esc(b.name||"Catálogo")}"><meta property="og:description" content="${esc(b.tag||"Catálogo digital")}"><meta property="og:type" content="website"><title>${esc(b.name||"Catálogo")}</title><style>:root{--accent:${/^#[0-9a-f]{6}$/i.test(b.color)?b.color:"#1f6b52"};--paper:#f7f4ed;--ink:#17181b}*{box-sizing:border-box}body{margin:0;background:#111;color:var(--ink);font-family:system-ui,-apple-system,Segoe UI,sans-serif}.page{max-width:760px;margin:auto;background:var(--paper);min-height:100vh}.hero{background:var(--accent);color:#fff;padding:42px 24px}.hero img{width:64px;height:64px;object-fit:cover;border-radius:16px;margin-bottom:18px}.hero small{text-transform:uppercase;letter-spacing:.12em;opacity:.75}.hero h1{font-size:40px;line-height:1;margin:8px 0}.hero p{margin:0;opacity:.85}.body{padding:20px}.location{font-size:13px;color:#777;margin-bottom:16px}.items{display:grid;gap:10px}.item{display:grid;grid-template-columns:64px 1fr auto;gap:12px;align-items:center;background:#fff;border:1px solid #e6e1d8;border-radius:16px;padding:12px}.thumb{width:64px;height:64px;border-radius:12px;background:#eee8dc;display:grid;place-items:center;font-size:25px;overflow:hidden}.thumb img{width:100%;height:100%;object-fit:cover}.item h2{font-size:15px;margin:0 0 4px}.item p{font-size:12px;color:#777;margin:0}.price{white-space:nowrap}.info{margin-top:14px;padding:14px;border-radius:14px;background:#ebe7df;font-size:12px}.info b{display:block;margin-bottom:5px}.cta{display:block;text-align:center;margin-top:14px;padding:15px;border-radius:14px;background:#17181b;color:#fff;text-decoration:none;font-weight:800}.footer{text-align:center;color:#999;font-size:10px;padding:24px}</style></head><body><main class="page"><header class="hero">${b.logo?`<img src="${b.logo}" alt="">`:""}<small>Catálogo digital</small><h1>${esc(b.name||"Catálogo")}</h1><p>${esc(b.tag||"")}</p></header><section class="body">${a.showLocation&&b.address?`<div class="location">📍 ${esc(b.address)}</div>`:""}<div class="items">${items}</div>${a.showInfo&&((b.hours||b.payment||b.delivery))?`<div class="info">${b.hours?`<b>Horarios</b>${esc(b.hours)}<br>`:""}${b.payment?`<b>Medios de pago</b>${esc(b.payment)}<br>`:""}${b.delivery?`<b>Entrega</b>${esc(b.delivery)}`:""}</div>`:""}${waUrl!=="#"?`<a class="cta" href="${waUrl}">${esc(a.buttonText||"Pedir por WhatsApp")}</a>`:""}</section><footer class="footer">Catálogo creado con Catálogo Express · Ocarina Producciones</footer></main></body></html>`
}
function esc(v){return String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]))}
