"use client";

import { ChangeEvent, useEffect, useMemo, useState } from "react";
import type { CSSProperties, ReactNode } from "react";
import { Catalog as CatalogType, Item, MAX_ITEMS, instagramUsername, safeExternalUrl, whatsappPhone } from "../lib/catalog";

type Catalog = CatalogType;
const starter:Catalog={business:"Tu negocio",subtitle:"Catálogo digital",description:"Presentá tus productos o servicios de forma clara, profesional y lista para compartir.",logo:"",phone:"",whatsapp:"",instagram:"",website:"",location:"",primary:"#172033",secondary:"#f5f3ee",template:"elegante",items:[{id:"1",name:"Producto destacado",description:"Descripción comercial breve y concreta.",price:"$ 0",category:"Destacados",image:"",tag:"Nuevo"},{id:"2",name:"Servicio profesional",description:"Explicá qué incluye y por qué conviene contratarlo.",price:"Consultar",category:"Servicios",image:"",tag:"Recomendado"}]};
const KEY="catalogo-studio-v3";
const uid=()=>crypto.randomUUID?.()||Math.random().toString(36).slice(2);
function fileToDataUrl(file:File,max=1200){return new Promise<string>((resolve,reject)=>{if(!file.type.startsWith("image/"))return reject(new Error("Formato inválido"));if(file.size>8*1024*1024)return reject(new Error("Imagen demasiado grande"));const r=new FileReader();r.onload=()=>{const src=String(r.result);const img=new Image();img.onload=()=>{const scale=Math.min(1,max/Math.max(img.width,img.height));const w=Math.max(1,Math.round(img.width*scale)),h=Math.max(1,Math.round(img.height*scale));const canvas=document.createElement("canvas");canvas.width=w;canvas.height=h;const ctx=canvas.getContext("2d");if(!ctx)return reject(new Error("No se pudo procesar la imagen"));ctx.drawImage(img,0,0,w,h);resolve(canvas.toDataURL("image/jpeg",.82))};img.onerror=()=>reject(new Error("Imagen inválida"));img.src=src};r.onerror=()=>reject(new Error("No se pudo leer la imagen"));r.readAsDataURL(file)})}

export default function Home(){
 const [c,setC]=useState<Catalog>(starter); const [saved,setSaved]=useState(false); const [notice,setNotice]=useState(""); const [publishedUrl,setPublishedUrl]=useState(""); const [publishing,setPublishing]=useState(false);
 useEffect(()=>{try{const x=localStorage.getItem(KEY);if(x)setC(JSON.parse(x));}catch{setNotice("No se pudo recuperar el catálogo guardado")}},[]);
 const cats=useMemo(()=>Array.from(new Set(c.items.map(x=>(x.category||"").trim()||"General"))),[c.items]);
 const patch=(p:Partial<Catalog>)=>{setC(x=>({...x,...p}));setSaved(false)};
 const update=(id:string,p:Partial<Item>)=>{setC(x=>({...x,items:x.items.map(i=>i.id===id?{...i,...p}:i)}));setSaved(false)};
 const add=()=>{if(c.items.length>=MAX_ITEMS){setNotice(`Límite alcanzado: ${MAX_ITEMS} ítems por catálogo`);return}setC(x=>({...x,items:[...x.items,{id:uid(),name:"Nuevo producto",description:"Descripción comercial",price:"Consultar",category:"General",image:"",tag:""}]}));setSaved(false)};
 const duplicate=(id:string)=>{if(c.items.length>=MAX_ITEMS){setNotice(`Límite alcanzado: ${MAX_ITEMS} ítems por catálogo`);return}setC(x=>{const i=x.items.find(y=>y.id===id);if(!i)return x;const n={...i,id:uid(),name:i.name+" (copia)"};const a=[...x.items];a.splice(a.findIndex(y=>y.id===id)+1,0,n);return {...x,items:a}});setSaved(false)};
 const move=(id:string,d:number)=>{setC(x=>{const a=[...x.items],i=a.findIndex(y=>y.id===id),j=i+d;if(i<0||j<0||j>=a.length)return x;[a[i],a[j]]=[a[j],a[i]];return {...x,items:a}});setSaved(false)};
 const remove=(id:string)=>{setC(x=>({...x,items:x.items.filter(i=>i.id!==id)}));setSaved(false)};
 const save=()=>{try{localStorage.setItem(KEY,JSON.stringify(c));setSaved(true);setNotice("Catálogo guardado en este dispositivo")}catch{setNotice("No se pudo guardar: reducÍ el tamaño de alguna imagen")}};
 const reset=()=>{if(confirm("¿Restaurar el catálogo inicial? Se perderán los cambios locales.")){setC(starter);localStorage.removeItem(KEY);setSaved(false);setPublishedUrl("");setNotice("Catálogo restaurado")}};
 const exportJson=()=>{const a=document.createElement("a"),u=URL.createObjectURL(new Blob([JSON.stringify(c,null,2)],{type:"application/json"}));a.href=u;a.download=(c.business||"catalogo").toLowerCase().replace(/[^a-z0-9]+/g,"-")+".json";a.click();URL.revokeObjectURL(u)};
 const importJson=(e:ChangeEvent<HTMLInputElement>)=>{const f=e.target.files?.[0];if(!f)return;const r=new FileReader();r.onload=()=>{try{const x=JSON.parse(String(r.result));if(!x.business||!Array.isArray(x.items)||x.items.length>MAX_ITEMS)throw 0;setC({...starter,...x});setSaved(false);setPublishedUrl("");setNotice("Catálogo importado correctamente")}catch{setNotice("Archivo inválido o supera el límite de 100 ítems")}};r.readAsText(f);e.target.value=""};
 const uploadLogo=async(e:ChangeEvent<HTMLInputElement>)=>{const f=e.target.files?.[0];if(!f)return;try{patch({logo:await fileToDataUrl(f,700)});setNotice("Logo cargado")}catch(error){setNotice(error instanceof Error?error.message:"No se pudo cargar el logo")}finally{e.target.value=""}};
 const uploadItem=async(id:string,e:ChangeEvent<HTMLInputElement>)=>{const f=e.target.files?.[0];if(!f)return;try{update(id,{image:await fileToDataUrl(f,1200)});setNotice("Imagen cargada")}catch(error){setNotice(error instanceof Error?error.message:"No se pudo cargar la imagen")}finally{e.target.value=""}};
 const publish=async()=>{if(!c.business.trim()){setNotice("Primero completá el nombre del negocio");return}if(!c.whatsapp.trim()){setNotice("Agregá el WhatsApp del negocio antes de publicar");return}if(!c.items.length){setNotice("Agregá al menos un producto o servicio");return}try{setPublishing(true);localStorage.setItem(KEY,JSON.stringify(c));const res=await fetch("/api/catalogs",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(c)});const data=await res.json().catch(()=>({}));if(!res.ok)throw new Error(data.detail||data.error||"No se pudo publicar");const url=new URL(data.url,window.location.origin).toString();setPublishedUrl(url);await navigator.clipboard?.writeText(url);setNotice("Publicado correctamente. El link quedó copiado")}catch(error){console.error(error);setNotice(error instanceof Error?error.message:"No se pudo publicar. Revisá la conexión de Vercel Blob")}finally{setPublishing(false)}};
 const copyPublished=async()=>{if(!publishedUrl)return;await navigator.clipboard?.writeText(publishedUrl);setNotice("Link copiado")};
 return <div className="app"><header className="top"><div className="brand"><b>CS</b><strong>Catálogo Studio</strong><span>Constructor profesional</span></div><div className="actions"><button onClick={reset}>Restaurar</button><label>Importar<input hidden type="file" accept="application/json" onChange={importJson}/></label><button onClick={exportJson}>Exportar</button><button onClick={()=>window.print()}>PDF / Imprimir</button><button onClick={publish} className="publish" disabled={publishing}>{publishing?"Publicando…":"Publicar online"}</button><button className="primary" onClick={save}>{saved?"Guardado ✓":"Guardar"}</button></div></header>
 <div className="workspace"><aside className="panel"><div className="panel-head"><div><small>PROYECTO ACTIVO</small><h1>Construí tu catálogo</h1></div><span className="status">● EDITABLE</span></div><div className="progress"><span style={{width:`${Math.min(100,25+(c.items.length>0?35:0)+(c.business!==starter.business?20:0)+(c.whatsapp||c.phone?20:0))}%`}}/></div>
 {publishedUrl&&<div className="published-box"><strong>✓ Catálogo online publicado</strong><input readOnly value={publishedUrl}/><div><button onClick={copyPublished}>Copiar link</button><a href={publishedUrl} target="_blank" rel="noreferrer">Abrir catálogo</a></div></div>}
 <Section title="01 · Identidad"><Field label="Nombre del negocio"><input value={c.business} onChange={e=>patch({business:e.target.value})}/></Field><Field label="Bajada"><input value={c.subtitle} onChange={e=>patch({subtitle:e.target.value})}/></Field><Field label="Descripción"><textarea value={c.description} onChange={e=>patch({description:e.target.value})}/></Field><Field label="Logo"><input placeholder="https://..." value={c.logo.startsWith("data:")?"Imagen cargada":c.logo} onChange={e=>patch({logo:e.target.value})}/><label className="upload">＋ Cargar logo<input hidden type="file" accept="image/*" onChange={uploadLogo}/></label></Field></Section>
 <Section title="02 · Contacto"><Field label="WhatsApp"><input placeholder="299 1234567" value={c.whatsapp} onChange={e=>patch({whatsapp:e.target.value})}/></Field><Field label="Teléfono"><input value={c.phone} onChange={e=>patch({phone:e.target.value})}/></Field><Field label="Instagram"><input placeholder="@tuusuario" value={c.instagram} onChange={e=>patch({instagram:e.target.value})}/></Field><Field label="Sitio web"><input placeholder="https://tusitio.com" value={c.website} onChange={e=>patch({website:e.target.value})}/></Field><Field label="Ubicación"><input value={c.location} onChange={e=>patch({location:e.target.value})}/></Field></Section>
 <Section title="03 · Diseño"><div className="templates">{(["elegante","comercial","minimal"] as const).map(t=><button key={t} className={c.template===t?"selected":""} onClick={()=>patch({template:t})}><i className={`swatch ${t}`}/>{t}</button>)}</div><div className="colors"><Field label="Principal"><input type="color" value={c.primary} onChange={e=>patch({primary:e.target.value})}/></Field><Field label="Fondo"><input type="color" value={c.secondary} onChange={e=>patch({secondary:e.target.value})}/></Field></div></Section>
 <Section title={`04 · Contenido · ${c.items.length} ítems`}>{c.items.map((i,n)=><div className="item" key={i.id}><div className="itembar"><b>{String(n+1).padStart(2,"0")} · {i.name||"Sin nombre"}</b><div><button title="Subir" onClick={()=>move(i.id,-1)}>↑</button><button title="Bajar" onClick={()=>move(i.id,1)}>↓</button><button title="Duplicar" onClick={()=>duplicate(i.id)}>＋</button><button className="danger" onClick={()=>remove(i.id)}>×</button></div></div><Field label="Nombre"><input value={i.name} onChange={e=>update(i.id,{name:e.target.value})}/></Field><Field label="Categoría"><input value={i.category} onChange={e=>update(i.id,{category:e.target.value})}/></Field><Field label="Descripción"><textarea value={i.description} onChange={e=>update(i.id,{description:e.target.value})}/></Field><div className="two"><Field label="Precio / modalidad"><input value={i.price} onChange={e=>update(i.id,{price:e.target.value})}/></Field><Field label="Etiqueta"><input value={i.tag} placeholder="Oferta" onChange={e=>update(i.id,{tag:e.target.value})}/></Field></div><Field label="Imagen"><input placeholder="https://..." value={i.image.startsWith("data:")?"Imagen cargada":i.image} onChange={e=>update(i.id,{image:e.target.value})}/><label className="upload">＋ Cargar imagen<input hidden type="file" accept="image/*" onChange={e=>uploadItem(i.id,e)}/></label></Field></div>)}<button className="add" onClick={add}>＋ Agregar producto o servicio</button></Section>
 <div className="locked">✓ V5 · núcleo consolidado · publicación online · WhatsApp · PDF · importación/exportación</div></aside><main className="preview"><div className="preview-head"><span>VISTA PREVIA EN TIEMPO REAL</span><span>{c.items.length} ítems · {cats.length} categorías</span></div><Catalog c={c} cats={cats}/>{notice&&<div className="toast" onClick={()=>setNotice("")}>{notice}</div>}</main></div></div>
}
function Section({title,children}:{title:string;children:ReactNode}){return <section className="section"><h2>{title}</h2>{children}</section>}
function Field({label,children}:{label:string;children:ReactNode}){return <label className="field"><span>{label}</span>{children}</label>}
function Catalog({c,cats}:{c:Catalog;cats:string[]}){const wa=whatsappPhone(c.whatsapp);const ig=instagramUsername(c.instagram);const web=safeExternalUrl(c.website);return <article className={`catalog ${c.template}`} style={{"--primary":c.primary,"--secondary":c.secondary} as CSSProperties}><header className="cover"><div className="cover-brand">{c.logo?<img src={c.logo} alt="Logo"/>:<span className="logo-fallback">{(c.business||"N").slice(0,1).toUpperCase()}</span>}<span>{c.subtitle||"Catálogo digital"}</span></div><div className="cover-copy"><small>CATÁLOGO · {new Date().getFullYear()}</small><h3>{c.business||"Tu negocio"}</h3><p>{c.description}</p></div><div className="contact"><Link href={wa?`https://wa.me/${wa}`:""} active={!!wa}>WhatsApp</Link><Link href={c.phone?`tel:${c.phone.replace(/[^\d+]/g,"")}:""} active={!!c.phone}>Llamar</Link><Link href={ig?`https://instagram.com/${ig}`:""} active={!!ig}>Instagram</Link><Link href={web} active={!!web}>Web</Link>{c.location&&<span>{c.location}</span>}</div></header><div className="body">{cats.map(cat=><section className="cat" key={cat}><div className="cat-title"><span>{cat}</span><i/></div><div className="grid">{c.items.filter(i=>(i.category||"General").trim()===cat).map(i=><div className="card" key={i.id}><div className="image">{i.image?<img src={i.image} alt={i.name} loading="lazy"/>:<span>{(i.name||"P").slice(0,1).toUpperCase()}</span>}</div><div className="card-body"><div className="tagline">{i.tag||""}</div><h4>{i.name||"Producto"}</h4><p>{i.description||"Sin descripción."}</p><div className="bottom"><strong>{i.price||"Consultar"}</strong>{wa&&<a href={`https://wa.me/${wa}?text=${encodeURIComponent(`Hola, consulto por ${i.name||"un producto"}`)}`} target="_blank" rel="noreferrer">Consultar →</a>}</div></div></div>)}</div></section>)}{!c.items.length&&<div className="empty">Agregá el primer producto o servicio desde el constructor.</div>}<footer>{c.business||"Tu negocio"} · Catálogo digital · {web||c.phone||wa||"Contacto disponible"}</footer></div></article>}
function Link({href,active,children}:{href:string;active:boolean;children:ReactNode}){return active?<a href={href} target={href.startsWith("http")?"_blank":undefined} rel="noreferrer">{children}</a>:<span className="disabled">{children}</span>}
